[package]
name = "rssearch"
version = "0.1.0"
authors = ["Cary Clark <clarkcb@gmail.com>"]
edition = "2018"

[dependencies]
encoding = "0.2.33"
regex = "1.3.1"
serde = { version ="1.0.103", features = ["derive"] }
serde_json = "1.0.42"
walkdir = "2.2.9"
zip = "0.5.3"
