name: dartsearch
description: A sample command-line application.
# version: 1.0.0
# homepage: https://github.com/clarkcb/xsearch
# repository: https://github.com/clarkcb/xsearch

environment:
  sdk: '>=2.19.0 <3.11.0'

dependencies:
  dartfind:
    path: ../../../xfind/dart/dartfind

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
